---

- name: Launch new EC2 Instance
  local_action:
    module: ec2
    group: "{{aws_security_group}}"
    instance_type: "{{aws_instance_type}}"
    image: "{{aws_image}}"
    wait: true
    region: "{{aws_region}}"
    keypair: "{{aws_keypair}}"
    vpc_subnet_id: "{{aws_vpc_subnet_id}}"
    count: 1
    #spot_price: "{{aws_spot_price}}"
    #spot_type: "{{aws_spot_type}}"
    #spot_wait_timeout: "{{aws_spot_wait_timeout}}"
    #spot_launch_group: "{{aws_spot_launch_group}}"
    assign_public_ip: yes
    instance_tags: '{"Name":"{{ec2_tag_Name}}","Type":"{{ec2_tag_Type}}","Environment":"{{ec2_tag_Environment}}"}'
  register: ec2

- debug: var=item
  with_items: "{{ec2.instances}}"

- add_host: name={{item.public_ip }} >
             groups=tag_Type_{{ec2_tag_Type}},tag_Environment_{{ec2_tag_Environment}}
             ec2_region={{aws_region}}
             ec2_tag_Name={{ec2_tag_Name}}
             ec2_tag_Type={{ec2_tag_Type}}
             ec2_tag_Environment={{ec2_tag_Environment}}
             ec2_ip_address={{item.public_ip}}
  with_items: "{{ec2.instances}}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{item.public_ip}}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"
